services:
  prefect:
    image: prefecthq/prefect:2.14-python3.12
    ports:
      - "4200:4200"
    command: prefect server start --host 0.0.0.0
    environment:
      - PREFECT_API_DATABASE_CONNECTION_URL=sqlite+aiosqlite:///home/prefect/.prefect/orion.db
    volumes:
      - prefect_data:/home/prefect/.prefect
    restart: unless-stopped

volumes:
  prefect_data: